name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  DEFAULT_NODE_VERSION: "16"

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Check Lint
        run: yarn lint
