name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  DEFAULT_NODE_VERSION: "16"

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Generate npmrc
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@hyesungoh:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "@GDSC-SKHU:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.HYESUNG_PACKAGES_READ }}" >> .npmrc

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Lint
        run: yarn lint
