name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  DEFAULT_NODE_VERSION: "16"

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Lint
        run: yarn lint
