name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2

      - name: Generate npmrc
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@hyesungoh:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "@GDSC-SKHU:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.HYESUNG_PACKAGES_READ }}" >> .npmrc

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Hosting with firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BAKKU_WEB }}"
          projectId: bakku-web
